# Generated by Django 2.1.3 on 2018-12-04 01:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
