# Generated by Django 2.1.3 on 2018-12-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181204_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
    ]
